# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Project/project_lte_receiver/project_lte_receiver.srcs/sources_1/ip/fir_compiler_3/fir_compiler_3.xci
# IP: The module: 'fir_compiler_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/project_lte_receiver/project_lte_receiver.gen/sources_1/ip/fir_compiler_3/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/project_lte_receiver/project_lte_receiver.gen/sources_1/ip/fir_compiler_3/fir_compiler_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Project/project_lte_receiver/project_lte_receiver.srcs/sources_1/ip/fir_compiler_3/fir_compiler_3.xci
# IP: The module: 'fir_compiler_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/project_lte_receiver/project_lte_receiver.gen/sources_1/ip/fir_compiler_3/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Project/project_lte_receiver/project_lte_receiver.gen/sources_1/ip/fir_compiler_3/fir_compiler_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
